# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Neehaarika's Home Page
url:              http://velavar.github.io
baseurl:          /

paginate:         5

github:
  repo:           https://github.com/velavar
